/*
Navicat MySQL Data Transfer

Source Server         : RsPi
Source Server Version : 50528
Source Host           : 192.168.1.113:3306
Source Database       : demo

Target Server Type    : MYSQL
Target Server Version : 50528
File Encoding         : 65001

Date: 2013-10-23 23:14:46
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for datas
-- ----------------------------
DROP TABLE IF EXISTS `datas`;
CREATE TABLE `datas` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `url_id` int(10) unsigned NOT NULL,
  `field_id` int(10) unsigned NOT NULL,
  `value` text NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `url_field_id` (`field_id`,`url_id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=501 DEFAULT CHARSET=utf8 COMMENT='Значение полей';

-- ----------------------------
-- Records of datas
-- ----------------------------
INSERT INTO `datas` VALUES ('1', '1', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('2', '1', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('3', '1', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('4', '1', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('5', '1', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('6', '1', '6', '32год');
INSERT INTO `datas` VALUES ('7', '1', '7', 'мужской');
INSERT INTO `datas` VALUES ('8', '1', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('9', '1', '9', 'нет');
INSERT INTO `datas` VALUES ('10', '1', '10', '12год');
INSERT INTO `datas` VALUES ('11', '1', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('12', '1', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('13', '1', '13', '2год');
INSERT INTO `datas` VALUES ('14', '1', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('15', '1', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('16', '1', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('17', '1', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('18', '1', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('19', '1', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('20', '1', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('21', '2', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('22', '2', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('23', '2', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('24', '2', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('25', '2', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('26', '2', '6', '32год');
INSERT INTO `datas` VALUES ('27', '2', '7', 'мужской');
INSERT INTO `datas` VALUES ('28', '2', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('29', '2', '9', 'нет');
INSERT INTO `datas` VALUES ('30', '2', '10', '12год');
INSERT INTO `datas` VALUES ('31', '2', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('32', '2', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('33', '2', '13', '2год');
INSERT INTO `datas` VALUES ('34', '2', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('35', '2', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('36', '2', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('37', '2', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('38', '2', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('39', '2', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('40', '2', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('41', '3', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('42', '3', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('43', '3', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('44', '3', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('45', '3', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('46', '3', '6', '32год');
INSERT INTO `datas` VALUES ('47', '3', '7', 'мужской');
INSERT INTO `datas` VALUES ('48', '3', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('49', '3', '9', 'нет');
INSERT INTO `datas` VALUES ('50', '3', '10', '12год');
INSERT INTO `datas` VALUES ('51', '3', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('52', '3', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('53', '3', '13', '2год');
INSERT INTO `datas` VALUES ('54', '3', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('55', '3', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('56', '3', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('57', '3', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('58', '3', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('59', '3', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('60', '3', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('61', '4', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('62', '4', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('63', '4', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('64', '4', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('65', '4', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('66', '4', '6', '32год');
INSERT INTO `datas` VALUES ('67', '4', '7', 'мужской');
INSERT INTO `datas` VALUES ('68', '4', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('69', '4', '9', 'нет');
INSERT INTO `datas` VALUES ('70', '4', '10', '12год');
INSERT INTO `datas` VALUES ('71', '4', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('72', '4', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('73', '4', '13', '2год');
INSERT INTO `datas` VALUES ('74', '4', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('75', '4', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('76', '4', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('77', '4', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('78', '4', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('79', '4', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('80', '4', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('81', '5', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('82', '5', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('83', '5', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('84', '5', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('85', '5', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('86', '5', '6', '32год');
INSERT INTO `datas` VALUES ('87', '5', '7', 'мужской');
INSERT INTO `datas` VALUES ('88', '5', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('89', '5', '9', 'нет');
INSERT INTO `datas` VALUES ('90', '5', '10', '12год');
INSERT INTO `datas` VALUES ('91', '5', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('92', '5', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('93', '5', '13', '2год');
INSERT INTO `datas` VALUES ('94', '5', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('95', '5', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('96', '5', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('97', '5', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('98', '5', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('99', '5', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('100', '5', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('101', '6', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('102', '6', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('103', '6', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('104', '6', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('105', '6', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('106', '6', '6', '32год');
INSERT INTO `datas` VALUES ('107', '6', '7', 'мужской');
INSERT INTO `datas` VALUES ('108', '6', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('109', '6', '9', 'нет');
INSERT INTO `datas` VALUES ('110', '6', '10', '12год');
INSERT INTO `datas` VALUES ('111', '6', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('112', '6', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('113', '6', '13', '2год');
INSERT INTO `datas` VALUES ('114', '6', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('115', '6', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('116', '6', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('117', '6', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('118', '6', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('119', '6', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('120', '6', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('121', '7', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('122', '7', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('123', '7', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('124', '7', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('125', '7', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('126', '7', '6', '32год');
INSERT INTO `datas` VALUES ('127', '7', '7', 'мужской');
INSERT INTO `datas` VALUES ('128', '7', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('129', '7', '9', 'нет');
INSERT INTO `datas` VALUES ('130', '7', '10', '12год');
INSERT INTO `datas` VALUES ('131', '7', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('132', '7', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('133', '7', '13', '2год');
INSERT INTO `datas` VALUES ('134', '7', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('135', '7', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('136', '7', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('137', '7', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('138', '7', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('139', '7', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('140', '7', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('141', '8', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('142', '8', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('143', '8', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('144', '8', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('145', '8', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('146', '8', '6', '32год');
INSERT INTO `datas` VALUES ('147', '8', '7', 'мужской');
INSERT INTO `datas` VALUES ('148', '8', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('149', '8', '9', 'нет');
INSERT INTO `datas` VALUES ('150', '8', '10', '12год');
INSERT INTO `datas` VALUES ('151', '8', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('152', '8', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('153', '8', '13', '2год');
INSERT INTO `datas` VALUES ('154', '8', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('155', '8', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('156', '8', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('157', '8', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('158', '8', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('159', '8', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('160', '8', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('161', '9', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('162', '9', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('163', '9', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('164', '9', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('165', '9', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('166', '9', '6', '32год');
INSERT INTO `datas` VALUES ('167', '9', '7', 'мужской');
INSERT INTO `datas` VALUES ('168', '9', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('169', '9', '9', 'нет');
INSERT INTO `datas` VALUES ('170', '9', '10', '12год');
INSERT INTO `datas` VALUES ('171', '9', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('172', '9', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('173', '9', '13', '2год');
INSERT INTO `datas` VALUES ('174', '9', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('175', '9', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('176', '9', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('177', '9', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('178', '9', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('179', '9', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('180', '9', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('181', '10', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('182', '10', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('183', '10', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('184', '10', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('185', '10', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('186', '10', '6', '32год');
INSERT INTO `datas` VALUES ('187', '10', '7', 'мужской');
INSERT INTO `datas` VALUES ('188', '10', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('189', '10', '9', 'нет');
INSERT INTO `datas` VALUES ('190', '10', '10', '12год');
INSERT INTO `datas` VALUES ('191', '10', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('192', '10', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('193', '10', '13', '2год');
INSERT INTO `datas` VALUES ('194', '10', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('195', '10', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('196', '10', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('197', '10', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('198', '10', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('199', '10', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('200', '10', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('201', '11', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('202', '11', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('203', '11', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('204', '11', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('205', '11', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('206', '11', '6', '32год');
INSERT INTO `datas` VALUES ('207', '11', '7', 'мужской');
INSERT INTO `datas` VALUES ('208', '11', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('209', '11', '9', 'нет');
INSERT INTO `datas` VALUES ('210', '11', '10', '12год');
INSERT INTO `datas` VALUES ('211', '11', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('212', '11', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('213', '11', '13', '2год');
INSERT INTO `datas` VALUES ('214', '11', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('215', '11', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('216', '11', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('217', '11', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('218', '11', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('219', '11', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('220', '11', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('221', '12', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('222', '12', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('223', '12', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('224', '12', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('225', '12', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('226', '12', '6', '32год');
INSERT INTO `datas` VALUES ('227', '12', '7', 'мужской');
INSERT INTO `datas` VALUES ('228', '12', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('229', '12', '9', 'нет');
INSERT INTO `datas` VALUES ('230', '12', '10', '12год');
INSERT INTO `datas` VALUES ('231', '12', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('232', '12', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('233', '12', '13', '2год');
INSERT INTO `datas` VALUES ('234', '12', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('235', '12', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('236', '12', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('237', '12', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('238', '12', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('239', '12', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('240', '12', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('241', '13', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('242', '13', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('243', '13', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('244', '13', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('245', '13', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('246', '13', '6', '32год');
INSERT INTO `datas` VALUES ('247', '13', '7', 'мужской');
INSERT INTO `datas` VALUES ('248', '13', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('249', '13', '9', 'нет');
INSERT INTO `datas` VALUES ('250', '13', '10', '12год');
INSERT INTO `datas` VALUES ('251', '13', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('252', '13', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('253', '13', '13', '2год');
INSERT INTO `datas` VALUES ('254', '13', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('255', '13', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('256', '13', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('257', '13', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('258', '13', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('259', '13', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('260', '13', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('261', '14', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('262', '14', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('263', '14', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('264', '14', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('265', '14', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('266', '14', '6', '32год');
INSERT INTO `datas` VALUES ('267', '14', '7', 'мужской');
INSERT INTO `datas` VALUES ('268', '14', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('269', '14', '9', 'нет');
INSERT INTO `datas` VALUES ('270', '14', '10', '12год');
INSERT INTO `datas` VALUES ('271', '14', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('272', '14', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('273', '14', '13', '2год');
INSERT INTO `datas` VALUES ('274', '14', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('275', '14', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('276', '14', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('277', '14', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('278', '14', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('279', '14', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('280', '14', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('281', '15', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('282', '15', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('283', '15', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('284', '15', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('285', '15', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('286', '15', '6', '32год');
INSERT INTO `datas` VALUES ('287', '15', '7', 'мужской');
INSERT INTO `datas` VALUES ('288', '15', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('289', '15', '9', 'нет');
INSERT INTO `datas` VALUES ('290', '15', '10', '12год');
INSERT INTO `datas` VALUES ('291', '15', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('292', '15', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('293', '15', '13', '2год');
INSERT INTO `datas` VALUES ('294', '15', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('295', '15', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('296', '15', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('297', '15', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('298', '15', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('299', '15', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('300', '15', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('301', '16', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('302', '16', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('303', '16', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('304', '16', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('305', '16', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('306', '16', '6', '32год');
INSERT INTO `datas` VALUES ('307', '16', '7', 'мужской');
INSERT INTO `datas` VALUES ('308', '16', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('309', '16', '9', 'нет');
INSERT INTO `datas` VALUES ('310', '16', '10', '12год');
INSERT INTO `datas` VALUES ('311', '16', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('312', '16', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('313', '16', '13', '2год');
INSERT INTO `datas` VALUES ('314', '16', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('315', '16', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('316', '16', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('317', '16', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('318', '16', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('319', '16', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('320', '16', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('321', '17', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('322', '17', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('323', '17', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('324', '17', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('325', '17', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('326', '17', '6', '32год');
INSERT INTO `datas` VALUES ('327', '17', '7', 'мужской');
INSERT INTO `datas` VALUES ('328', '17', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('329', '17', '9', 'нет');
INSERT INTO `datas` VALUES ('330', '17', '10', '12год');
INSERT INTO `datas` VALUES ('331', '17', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('332', '17', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('333', '17', '13', '2год');
INSERT INTO `datas` VALUES ('334', '17', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('335', '17', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('336', '17', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('337', '17', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('338', '17', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('339', '17', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('340', '17', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('341', '18', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('342', '18', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('343', '18', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('344', '18', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('345', '18', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('346', '18', '6', '32год');
INSERT INTO `datas` VALUES ('347', '18', '7', 'мужской');
INSERT INTO `datas` VALUES ('348', '18', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('349', '18', '9', 'нет');
INSERT INTO `datas` VALUES ('350', '18', '10', '12год');
INSERT INTO `datas` VALUES ('351', '18', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('352', '18', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('353', '18', '13', '2год');
INSERT INTO `datas` VALUES ('354', '18', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('355', '18', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('356', '18', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('357', '18', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('358', '18', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('359', '18', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('360', '18', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('361', '19', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('362', '19', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('363', '19', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('364', '19', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('365', '19', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('366', '19', '6', '32год');
INSERT INTO `datas` VALUES ('367', '19', '7', 'мужской');
INSERT INTO `datas` VALUES ('368', '19', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('369', '19', '9', 'нет');
INSERT INTO `datas` VALUES ('370', '19', '10', '12год');
INSERT INTO `datas` VALUES ('371', '19', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('372', '19', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('373', '19', '13', '2год');
INSERT INTO `datas` VALUES ('374', '19', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('375', '19', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('376', '19', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('377', '19', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('378', '19', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('379', '19', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('380', '19', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('381', '20', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('382', '20', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('383', '20', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('384', '20', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('385', '20', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('386', '20', '6', '32год');
INSERT INTO `datas` VALUES ('387', '20', '7', 'мужской');
INSERT INTO `datas` VALUES ('388', '20', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('389', '20', '9', 'нет');
INSERT INTO `datas` VALUES ('390', '20', '10', '12год');
INSERT INTO `datas` VALUES ('391', '20', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('392', '20', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('393', '20', '13', '2год');
INSERT INTO `datas` VALUES ('394', '20', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('395', '20', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('396', '20', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('397', '20', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('398', '20', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('399', '20', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('400', '20', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('401', '21', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('402', '21', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('403', '21', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('404', '21', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('405', '21', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('406', '21', '6', '32год');
INSERT INTO `datas` VALUES ('407', '21', '7', 'мужской');
INSERT INTO `datas` VALUES ('408', '21', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('409', '21', '9', 'нет');
INSERT INTO `datas` VALUES ('410', '21', '10', '12год');
INSERT INTO `datas` VALUES ('411', '21', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('412', '21', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('413', '21', '13', '2год');
INSERT INTO `datas` VALUES ('414', '21', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('415', '21', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('416', '21', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('417', '21', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('418', '21', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('419', '21', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('420', '21', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('421', '22', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('422', '22', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('423', '22', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('424', '22', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('425', '22', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('426', '22', '6', '32год');
INSERT INTO `datas` VALUES ('427', '22', '7', 'мужской');
INSERT INTO `datas` VALUES ('428', '22', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('429', '22', '9', 'нет');
INSERT INTO `datas` VALUES ('430', '22', '10', '12год');
INSERT INTO `datas` VALUES ('431', '22', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('432', '22', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('433', '22', '13', '2год');
INSERT INTO `datas` VALUES ('434', '22', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('435', '22', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('436', '22', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('437', '22', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('438', '22', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('439', '22', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('440', '22', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('441', '23', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('442', '23', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('443', '23', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('444', '23', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('445', '23', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('446', '23', '6', '32год');
INSERT INTO `datas` VALUES ('447', '23', '7', 'мужской');
INSERT INTO `datas` VALUES ('448', '23', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('449', '23', '9', 'нет');
INSERT INTO `datas` VALUES ('450', '23', '10', '12год');
INSERT INTO `datas` VALUES ('451', '23', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('452', '23', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('453', '23', '13', '2год');
INSERT INTO `datas` VALUES ('454', '23', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('455', '23', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('456', '23', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('457', '23', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('458', '23', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('459', '23', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('460', '23', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('461', '24', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('462', '24', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('463', '24', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('464', '24', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('465', '24', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('466', '24', '6', '32год');
INSERT INTO `datas` VALUES ('467', '24', '7', 'мужской');
INSERT INTO `datas` VALUES ('468', '24', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('469', '24', '9', 'нет');
INSERT INTO `datas` VALUES ('470', '24', '10', '12год');
INSERT INTO `datas` VALUES ('471', '24', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('472', '24', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('473', '24', '13', '2год');
INSERT INTO `datas` VALUES ('474', '24', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('475', '24', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('476', '24', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('477', '24', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('478', '24', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('479', '24', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('480', '24', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');
INSERT INTO `datas` VALUES ('481', '25', '2', 'Ищу работу на должность IT-менеджер-специалист, Системный администратор, по специальности IT-специалист, Системный администратор, образование: средне-техническое, стаж (лет): 12, занятость: полный рабочий день, пол: мужской, возраст (лет): 32');
INSERT INTO `datas` VALUES ('482', '25', '3', 'Ташкент');
INSERT INTO `datas` VALUES ('483', '25', '1', 'Системный администратор');
INSERT INTO `datas` VALUES ('484', '25', '4', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('485', '25', '5', 'свободный график, неполный рабочий день, полный рабочий день');
INSERT INTO `datas` VALUES ('486', '25', '6', '32год');
INSERT INTO `datas` VALUES ('487', '25', '7', 'мужской');
INSERT INTO `datas` VALUES ('488', '25', '8', 'женат/замужем');
INSERT INTO `datas` VALUES ('489', '25', '9', 'нет');
INSERT INTO `datas` VALUES ('490', '25', '10', '12год');
INSERT INTO `datas` VALUES ('491', '25', '11', 'Системный администратор, IT-специалист');
INSERT INTO `datas` VALUES ('492', '25', '12', 'Компьютерная фирма по профессиональному обслуживанию компьютеров');
INSERT INTO `datas` VALUES ('493', '25', '13', '2год');
INSERT INTO `datas` VALUES ('494', '25', '14', 'среднее, средне-специальное');
INSERT INTO `datas` VALUES ('495', '25', '15', 'Техникум им.Каланова');
INSERT INTO `datas` VALUES ('496', '25', '16', 'Информационные технология, тех. систеное обслуживание компьютеров');
INSERT INTO `datas` VALUES ('497', '25', '17', 'IT-специалист, Системный администратор');
INSERT INTO `datas` VALUES ('498', '25', '18', 'Английский, Узбекский, Русский');
INSERT INTO `datas` VALUES ('499', '25', '19', 'Эксперт');
INSERT INTO `datas` VALUES ('500', '25', '20', 'Профессиональное обслуживание, системно-техническое администрирование компьютеров и оргтехники, профилактика, диагностика, ремонт, сборка, модернизация, настройка, защита информации, чистка компьютеров от вирусов.\r\nЗаправка картриджей лазерных и копировальных аппаратов, Canon, HP, Samsung.\r\nВосстановление файлов после удаления и форматирования на жестких носителях, резервное копирование файлов.\r\nПроектирование, настройка, подключение, диагностика, локальной по протоколу TCP\\IP, 100Mb\\1Gb LAN (ЛВС), WAN (Wi-Fi), ADSL Интернет сети между компьютерами и оргтехникой.\r\nУстановка, настройка, восстановление операционных систем Microsoft Windows NT / Server-2003-2008 / XP / Vista / Seven.\r\nУстановка, настройка, программ Microsoft Office Word, Excel, PowerPoint, PictureManager, ABBYY Fine Reader, Adobe Reader, Photoshop, Corel Draw, Nero, Format Factory, Freemake Video Converter, TuneUp Utilities, Ccleaner, Total Commander, Hdd-Mem Test, R-Studio, NetMeter, NetTraffic, DUTraffic, BWMeter, IP Blocker, NetLimiter, NetWorx, WinProxy, ClubTimer, RunPadShell, KrawNet.\r\nУстановка антивирусов Nod32, Касперский, Avira, Dr.Web, Avast.\r\nПодключение к Интернету, установка, настройка программ по распределению и слежению за трафиком, создания отчётов по внешнему и TAS-IX трафику.\r\nУстановка, настройка, программ для работы в сети Интернет Internet Explorer, Mozilla Thunderbird, Mozilla Firefox, Opera, Google Chrome, Mail Agent, Skype, Download Master, UTorrent.');

-- ----------------------------
-- Table structure for fields
-- ----------------------------
DROP TABLE IF EXISTS `fields`;
CREATE TABLE `fields` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=utf8 COMMENT='Поля резюме';

-- ----------------------------
-- Records of fields
-- ----------------------------
INSERT INTO `fields` VALUES ('1', 'Специализация');
INSERT INTO `fields` VALUES ('2', 'Описание');
INSERT INTO `fields` VALUES ('3', 'Регион');
INSERT INTO `fields` VALUES ('4', 'Должность');
INSERT INTO `fields` VALUES ('5', 'Тип занятости');
INSERT INTO `fields` VALUES ('6', 'Возраст');
INSERT INTO `fields` VALUES ('7', 'Пол');
INSERT INTO `fields` VALUES ('8', 'Семейное положение');
INSERT INTO `fields` VALUES ('9', 'Дети');
INSERT INTO `fields` VALUES ('10', 'Стаж работы');
INSERT INTO `fields` VALUES ('11', 'Последняя занимаемая должность');
INSERT INTO `fields` VALUES ('12', 'Последнее место работы');
INSERT INTO `fields` VALUES ('13', 'Срок работы на последнем месте');
INSERT INTO `fields` VALUES ('14', 'Образование');
INSERT INTO `fields` VALUES ('15', 'Название учебного заведения');
INSERT INTO `fields` VALUES ('16', 'Факультет');
INSERT INTO `fields` VALUES ('17', 'Специальность');
INSERT INTO `fields` VALUES ('18', 'Знание иностранных языков');
INSERT INTO `fields` VALUES ('19', 'Знание компьютера');
INSERT INTO `fields` VALUES ('20', 'Дополнительно');

-- ----------------------------
-- Table structure for tasks
-- ----------------------------
DROP TABLE IF EXISTS `tasks`;
CREATE TABLE `tasks` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `url` varchar(2000) NOT NULL,
  `type` enum('list','page') NOT NULL,
  `status` enum('to_update','to_do','success','error') NOT NULL DEFAULT 'to_do',
  PRIMARY KEY (`id`),
  UNIQUE KEY `url` (`url`(333)) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=29 DEFAULT CHARSET=utf8 COMMENT='Страницы задачи для парсера';

-- ----------------------------
-- Records of tasks
-- ----------------------------
INSERT INTO `tasks` VALUES ('1', 'http://torg.uz/ru/offer/1783419', 'page', 'success');
INSERT INTO `tasks` VALUES ('2', 'http://torg.uz/ru/offer/1689033', 'page', 'success');
INSERT INTO `tasks` VALUES ('3', 'http://torg.uz/ru/offer/1752100', 'page', 'success');
INSERT INTO `tasks` VALUES ('4', 'http://torg.uz/ru/offer/1550491', 'page', 'success');
INSERT INTO `tasks` VALUES ('5', 'http://torg.uz/ru/offer/800789', 'page', 'success');
INSERT INTO `tasks` VALUES ('6', 'http://torg.uz/ru/offer/1704600', 'page', 'success');
INSERT INTO `tasks` VALUES ('7', 'http://torg.uz/ru/offer/1704602', 'page', 'success');
INSERT INTO `tasks` VALUES ('8', 'http://torg.uz/ru/offer/1027821', 'page', 'success');
INSERT INTO `tasks` VALUES ('9', 'http://torg.uz/ru/offer/1782325', 'page', 'success');
INSERT INTO `tasks` VALUES ('10', 'http://torg.uz/ru/offer/714945', 'page', 'success');
INSERT INTO `tasks` VALUES ('11', 'http://torg.uz/ru/offer/505057', 'page', 'success');
INSERT INTO `tasks` VALUES ('12', 'http://torg.uz/ru/offer/1671971', 'page', 'success');
INSERT INTO `tasks` VALUES ('13', 'http://torg.uz/ru/offer/1657463', 'page', 'success');
INSERT INTO `tasks` VALUES ('14', 'http://torg.uz/ru/offer/1718783', 'page', 'success');
INSERT INTO `tasks` VALUES ('15', 'http://torg.uz/ru/offer/978460', 'page', 'success');
INSERT INTO `tasks` VALUES ('16', 'http://torg.uz/ru/offer/1344060', 'page', 'success');
INSERT INTO `tasks` VALUES ('17', 'http://torg.uz/ru/offer/1294869', 'page', 'success');
INSERT INTO `tasks` VALUES ('18', 'http://torg.uz/ru/offer/1052422', 'page', 'success');
INSERT INTO `tasks` VALUES ('19', 'http://torg.uz/ru/offer/1502710', 'page', 'success');
INSERT INTO `tasks` VALUES ('20', 'http://torg.uz/ru/offer/832377', 'page', 'success');
INSERT INTO `tasks` VALUES ('21', 'http://torg.uz/ru/offer/1764627', 'page', 'success');
INSERT INTO `tasks` VALUES ('22', 'http://torg.uz/ru/offer/1691565', 'page', 'success');
INSERT INTO `tasks` VALUES ('23', 'http://torg.uz/ru/offer/1780548', 'page', 'success');
INSERT INTO `tasks` VALUES ('24', 'http://torg.uz/ru/offer/1532117', 'page', 'success');
INSERT INTO `tasks` VALUES ('25', 'http://torg.uz/ru/offer/1609923', 'page', 'success');
INSERT INTO `tasks` VALUES ('26', 'http://torg.uz/ru/catalog/programmisty-it-internet-rezyume/page/2', 'list', 'to_do');
INSERT INTO `tasks` VALUES ('27', 'http://torg.uz/ru/catalog/programmisty-it-internet-rezyume/page/3', 'list', 'to_do');
INSERT INTO `tasks` VALUES ('28', 'http://torg.uz/ru/catalog/programmisty-it-internet-rezyume/page/4', 'list', 'to_do');
